mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
mode: Rule
allow-lan: true
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
unified-delay: true
tcp-concurrent: true
enable-process: true
log-level: silent
find-process-mode: always
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
external-ui: /data/adb/box_bll/panel/Meta/
secret: "qjm123"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"

tun:
  enable: false
  device: tun0
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  route-exclude-address:
  - 192.168.0.0/16
  - fc00::/7
  exclude-package:
  - com.tencent.mm
  - com.tencent.tmgp.sgame

dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "connect.rom.miui.com"
    - "localhost.ptlogin2.qq.com"
  nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
    - tls://1.12.12.12
    - tls://120.53.53.53

  p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 900}}
  u: &u
    use:
    - 1.è‡ªå»º
    - 2.æœºåœº
    - 3.æœºåœº
    - 4.æœºåœº

proxy-providers:
  1.è‡ªå»º:
    <<: *p
    url: "https://gh.qjm01.dynv6.net/qianjianmin/Private-Library/main/zijian?token=qjm123"
    path: ./proxy_providers/subscribe1.yaml
  2.æœºåœº:
    <<: *p
    url: "http://dishujichang.xyz/api/v1/client/subscribe?token=a7c71e0e6a9df1b30fead9ee42ba7945"
    path: ./proxy_providers/subscribe2.yaml
  3.æœºåœº:
    <<: *p
    url: "https://bujidao.cc/sub?key=18Dz31ohsvHEjKJYCQa3TGtXP0T0ma9A"
    path: ./proxy_providers/subscribe3.yaml  
  4.æœºåœº:
    <<: *p
    url: "https://mydy.xlm.plus/api/v1/client/subscribe?token=265ef8608d516ef9656316fca51c4cab"
    path: ./proxy_providers/subscribe4.yaml    

proxies:
  - {name: ðŸŒŽ å…¨çƒç›´è¿ž, type: direct, udp: true}
  - {name: DNS_Hijack, type: dns}

proxy-groups:
  - {name: ðŸŽ¯ æ€»æ¨¡å¼, type: select, proxies: [ðŸš€ èŠ‚ç‚¹é€‰æ‹©,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,ðŸŒŽ å…¨çƒç›´è¿ž], <<: *u}
  - {name: â™»ï¸ å»¶è¿Ÿæœ€ä½Ž, <<: *u, type: url-test}
  - {name: â™»ï¸ æ•…éšœè½¬ç§», <<: *u, type: fallback}
  - {name: â™»ï¸ è´Ÿè½½å‡è¡¡, <<: *u, type: load-balance, strategy: round-robin}
  - {name: â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1, type: select, proxies: [ðŸš€ èŠ‚ç‚¹é€‰æ‹©,ðŸŒŽ å…¨çƒç›´è¿ž], <<: *u}
  - {name: â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2, type: select, proxies: [ðŸš€ èŠ‚ç‚¹é€‰æ‹©,ðŸŒŽ å…¨çƒç›´è¿ž], <<: *u}
  - {name: â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3, type: select, proxies: [ðŸš€ èŠ‚ç‚¹é€‰æ‹©,ðŸŒŽ å…¨çƒç›´è¿ž], <<: *u}
  - {name: ðŸ¤– OpenAI, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸ“± è„¸ä¹¦ç¤¾äº¤, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸ“² ç”µæŠ¥ä¿¡æ¯, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸŽ¬ æ²¹ç®¡åª’ä½“, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸ“¹ å¥ˆé£žåª’ä½“, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸ“¢ è°·æ­ŒæœåŠ¡, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸŽ è‹¹æžœæœåŠ¡, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸŽ® Discord, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸ“¸ å›½é™…æŠ–éŸ³, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸ“· ä¸­å›½æŠ–éŸ³ã€Œè¿›ç¨‹åŒ¹é…ã€, type: select, proxies: [ðŸŒŽ å…¨çƒç›´è¿ž,ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3]}
  - {name: ðŸŽ¹ ç½‘æ˜“éŸ³ä¹ã€Œè¿›ç¨‹åŒ¹é…ã€, type: select, proxies: [ðŸŒŽ å…¨çƒç›´è¿ž,ðŸŽ¯ æ€»æ¨¡å¼,â™»ï¸ å»¶è¿Ÿæœ€ä½Ž,â™»ï¸ æ•…éšœè½¬ç§»,â™»ï¸ è´Ÿè½½å‡è¡¡,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢1,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢2,â™»ï¸ æ‰‹åŠ¨åˆ‡æ¢3]}
  - {name: ðŸ›‘ å¹¿å‘Šæ‹¦æˆª, type: select, proxies: [REJECT,ðŸŒŽ å…¨çƒç›´è¿ž]}
  - {name: ðŸ‹ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ðŸŽ¯ æ€»æ¨¡å¼,ðŸŒŽ å…¨çƒç›´è¿ž]}

rule-providers:
  TikTok:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/TikTok.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/tiktok.yaml"
    interval: 86400
  Facebook:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Facebook.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/facebook.yaml"
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Telegram.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/telegram.yaml"
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/YouTube.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/youtube.yaml"
    interval: 86400
  Google:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Google.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/google.yaml"
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Microsoft.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/microsoft.yaml"
    interval: 86400
  Apple:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Apple.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/apple.yaml"
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/OpenAI.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/openai.yaml"
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Netflix.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/netflix.yaml"
    interval: 86400
  Discord:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Discord.yaml
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/classical/discord.yaml"
    interval: 86400

rules:
  - DST-PORT,53,DNS_Hijack
  - AND,((PROCESS-NAME,mihomo),(NOT,((IN-TYPE,inner)))),REJECT
  - AND,((PROCESS-NAME,clash),(NOT,((IN-TYPE,inner)))),REJECT
  - PROCESS-NAME,com.ss.android.ugc.aweme,ðŸ“· ä¸­å›½æŠ–éŸ³ã€Œè¿›ç¨‹åŒ¹é…ã€
  - PROCESS-NAME,com.netease.cloudmusic,ðŸŽ¹ ç½‘æ˜“éŸ³ä¹ã€Œè¿›ç¨‹åŒ¹é…ã€
  - RULE-SET,Discord,ðŸŽ® Discord
  - RULE-SET,TikTok,ðŸ“¸ å›½é™…æŠ–éŸ³
  - RULE-SET,YouTube,ðŸŽ¬ æ²¹ç®¡åª’ä½“
  - RULE-SET,Netflix,ðŸ“¹ å¥ˆé£žåª’ä½“
  - RULE-SET,Facebook,ðŸ“± è„¸ä¹¦ç¤¾äº¤
  - RULE-SET,OpenAI,ðŸ¤– OpenAI
  - RULE-SET,Google,ðŸ“¢ è°·æ­ŒæœåŠ¡
  - RULE-SET,Apple,ðŸŽ è‹¹æžœæœåŠ¡
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Telegram,ðŸ“² ç”µæŠ¥ä¿¡æ¯
  - GEOSITE,category-ads-all,ðŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - GEOSITE,CN,ðŸŒŽ å…¨çƒç›´è¿ž
  - GEOIP,CN,ðŸŒŽ å…¨çƒç›´è¿ž,no-resolve
  - GEOIP,private,ðŸŒŽ å…¨çƒç›´è¿ž,no-resolve
  - MATCH,ðŸ‹ æ¼ç½‘ä¹‹é±¼
